### ISSUE TITLE
App crashes after update check

### ISSUE THREAD

**Issue by mikehedman** [esper-io/esper-api-support-tool#134]
Hi, I'm not sure if it's the update check that's causing the problem, but each time I start the app it crashes immediately after displaying the update dialog:
<img width="495" alt="image" src="https://github.com/esper-io/esper-api-support-tool/assets/1550290/78f00e98-79b2-4fa7-9785-d51c9869cfb8">

I'm running the Arm64 pre-built version downloaded June 21, 2023. Running on an M1 Macbook Pro.

I did get through the tenant configuration, but then it shows the dialog and crashes.  I've tried removing the EsperApiTool folder and reinstalling and configuring, but that didn't change anything.

**Comment by jpfeatherston** [comment]
Hi Mike,

This issue should be fixed in the latest version. Unfortunately, this does mean that you will need to manually replace the downloaded executable, as the older version will continue to crash.

If you do continue to see this issue in the future. Please feel free to reopen the ticket.

You can find the latest version (as of this post) here: [https://github.com/esper-io/esper-api-support-tool/releases/tag/v0.19487](https://github.com/esper-io/esper-api-support-tool/releases/tag/v0.19487)

**Comment by mikehedman** [comment]
Works now, thanks!
